#pragma once

// Embedded ps2sdk IRX modules (generated by bin2c at build time)
#define IMPORT_BIN2C(_n) \
    extern unsigned char _n[]; \
    extern unsigned int size_##_n

IMPORT_BIN2C(sio2man_irx);

IMPORT_BIN2C(mcman_irx);

IMPORT_BIN2C(mcserv_irx);

IMPORT_BIN2C(padman_irx);

#ifndef DISABLE_PS2_AUDIO

IMPORT_BIN2C(freesd_irx);

IMPORT_BIN2C(audsrv_irx);

#endif // DISABLE_PS2_AUDIO
